apiVersion: v1
kind: Service
metadata:
  name: flask-app   # this is what default.conf looks for
  namespace: duo-task
  labels:
    app: flask
spec:
  selector:
    app: flask   # looking for pods with the label
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP