apiVersion: v1
kind: Service
metadata:
  name: nginx-LoadBalancer
  namespace: duo-task
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer